//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria_Precios
    {
        public short C__Lista_de_Precios { get; set; }
        public string Nombre_Listas_Precios { get; set; }
        public string Articulo_ { get; set; }
        public string Codigo_Auxiliar { get; set; }
        public string Proveedor { get; set; }
        public string Fabricante { get; set; }
        public string Descripcion { get; set; }
        public string Grupo_Articulos { get; set; }
        public Nullable<decimal> Tipo_Cambio { get; set; }
        public Nullable<decimal> Multiplicador { get; set; }
        public decimal Precio__ { get; set; }
        public decimal Precio_COL { get; set; }
        public decimal Costo__ { get; set; }
        public decimal Costo_COL { get; set; }
        public decimal Utilidad__ { get; set; }
        public decimal Utilidad_COL { get; set; }
        public decimal Precio_Sugerido__ { get; set; }
        public decimal Precio_Sugerido_COL { get; set; }
        public string Margen { get; set; }
        public Nullable<decimal> C__Margen { get; set; }
        public string Inactivo { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> Minimo { get; set; }
        public Nullable<decimal> Vendido { get; set; }
        public Nullable<decimal> C_CostovsFactura { get; set; }
        public Nullable<decimal> C_CostoNvsCostoA { get; set; }
        public string SubFamilia { get; set; }
        public string Clasificacion { get; set; }
    }
}
