//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZEBOLEntities : DbContext
    {
        public ZEBOLEntities()
            : base("name=ZEBOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria_Precios> Auditoria_Precios { get; set; }
        public virtual DbSet<CLVS_ART_PROB_SERIES> CLVS_ART_PROB_SERIES { get; set; }
        public virtual DbSet<CLVS_COBROS_GEN_AS_EST> CLVS_COBROS_GEN_AS_EST { get; set; }
        public virtual DbSet<CLVS_COBROS_GEN_COL> CLVS_COBROS_GEN_COL { get; set; }
        public virtual DbSet<CLVS_COMISIONES_LIN> CLVS_COMISIONES_LIN { get; set; }
        public virtual DbSet<CLVS_COMISIONES_LIN_V3> CLVS_COMISIONES_LIN_V3 { get; set; }
        public virtual DbSet<CLVS_COMISIONES_LIN_V4> CLVS_COMISIONES_LIN_V4 { get; set; }
        public virtual DbSet<CLVS_CONTROL_PROCESOS> CLVS_CONTROL_PROCESOS { get; set; }
        public virtual DbSet<CLVS_DOCUMENTOS_FE> CLVS_DOCUMENTOS_FE { get; set; }
        public virtual DbSet<CLVS_ENTREGASVSFACTURAS> CLVS_ENTREGASVSFACTURAS { get; set; }
        public virtual DbSet<CLVS_ESTADOS_GEN_EXP_V2> CLVS_ESTADOS_GEN_EXP_V2 { get; set; }
        public virtual DbSet<CLVS_FE_APPS_OV> CLVS_FE_APPS_OV { get; set; }
        public virtual DbSet<CLVS_FE_APPS_TRAMITE> CLVS_FE_APPS_TRAMITE { get; set; }
        public virtual DbSet<CLVS_Llamada_Control_Entregas> CLVS_Llamada_Control_Entregas { get; set; }
        public virtual DbSet<CLVS_LOG_TIEMPOS_FE> CLVS_LOG_TIEMPOS_FE { get; set; }
        public virtual DbSet<CLVS_OF> CLVS_OF { get; set; }
        public virtual DbSet<CLVS_OPORTUNIDADES_DET> CLVS_OPORTUNIDADES_DET { get; set; }
        public virtual DbSet<CLVS_ORDENES_ABIERTAS> CLVS_ORDENES_ABIERTAS { get; set; }
        public virtual DbSet<CLVS_OV_PagosRecibidos> CLVS_OV_PagosRecibidos { get; set; }
        public virtual DbSet<CLVS_PEDIDOS_STOCK> CLVS_PEDIDOS_STOCK { get; set; }
        public virtual DbSet<CLVS_RECEPCION_LINEAS_FE> CLVS_RECEPCION_LINEAS_FE { get; set; }
        public virtual DbSet<CLVS_ResumenDocsVentas> CLVS_ResumenDocsVentas { get; set; }
        public virtual DbSet<CLVS_SALES_ZP> CLVS_SALES_ZP { get; set; }
        public virtual DbSet<CLVS_TBL_OFERTAS_FACT> CLVS_TBL_OFERTAS_FACT { get; set; }
        public virtual DbSet<CLVS_TBL_PROCESO_VENTAS> CLVS_TBL_PROCESO_VENTAS { get; set; }
        public virtual DbSet<CLVS_TBL_TGT> CLVS_TBL_TGT { get; set; }
        public virtual DbSet<CLVS_TBL_VENTAS_SEG_NEGOCIO> CLVS_TBL_VENTAS_SEG_NEGOCIO { get; set; }
        public virtual DbSet<CLVS_TIZ_CANT_INV_ALMACEN> CLVS_TIZ_CANT_INV_ALMACEN { get; set; }
        public virtual DbSet<CLVS_TIZ_OFERTAS_ABIERTAS> CLVS_TIZ_OFERTAS_ABIERTAS { get; set; }
        public virtual DbSet<CLVS_TIZ_SOLICITUD_TRASLADOS> CLVS_TIZ_SOLICITUD_TRASLADOS { get; set; }
        public virtual DbSet<CLVS_VENTAS_DET> CLVS_VENTAS_DET { get; set; }
        public virtual DbSet<CLVS_VENTAS_DET_PAN> CLVS_VENTAS_DET_PAN { get; set; }
        public virtual DbSet<CLVS_VENTAS_DET_SC> CLVS_VENTAS_DET_SC { get; set; }
        public virtual DbSet<CLVS_ZEBOL_COMISIONES> CLVS_ZEBOL_COMISIONES { get; set; }
        public virtual DbSet<CLVSP_COBROS_DET> CLVSP_COBROS_DET { get; set; }
        public virtual DbSet<CLVSP_COBROS_GEN_COL_USD> CLVSP_COBROS_GEN_COL_USD { get; set; }
        public virtual DbSet<CLVSP_COBROS_GEN_COL_USD_PRUEBA> CLVSP_COBROS_GEN_COL_USD_PRUEBA { get; set; }
        public virtual DbSet<CLVSP_COD_BARRAS> CLVSP_COD_BARRAS { get; set; }
        public virtual DbSet<CLVSP_LISTA_UBICACIONES> CLVSP_LISTA_UBICACIONES { get; set; }
        public virtual DbSet<CLVSP_PEDIDOS_STOCK> CLVSP_PEDIDOS_STOCK { get; set; }
        public virtual DbSet<CLVSP_TRANSITO_MERCADERIAS> CLVSP_TRANSITO_MERCADERIAS { get; set; }
        public virtual DbSet<CLVSP_TST_LISTA_UBICACIONES> CLVSP_TST_LISTA_UBICACIONES { get; set; }
        public virtual DbSet<ConsultaDiariaOV> ConsultaDiariaOV { get; set; }
        public virtual DbSet<DYD_CDR_VIEW> DYD_CDR_VIEW { get; set; }
        public virtual DbSet<DYD_CONTROL_ETAPAS> DYD_CONTROL_ETAPAS { get; set; }
        public virtual DbSet<DyD_VENTAS_DET> DyD_VENTAS_DET { get; set; }
        public virtual DbSet<LLAMADA_SERVICIO> LLAMADA_SERVICIO { get; set; }
        public virtual DbSet<OITM> OITM { get; set; }
        public virtual DbSet<Pedido_Alistar> Pedido_Alistar { get; set; }
        public virtual DbSet<Pedido_Alistar_Mostrador> Pedido_Alistar_Mostrador { get; set; }
        public virtual DbSet<Solitud_Transfer> Solitud_Transfer { get; set; }
        public virtual DbSet<TIZ_NUMERO_SERIE_ALMACEN> TIZ_NUMERO_SERIE_ALMACEN { get; set; }
        public virtual DbSet<TRANSITO_MERCADERIAS> TRANSITO_MERCADERIAS { get; set; }
        public virtual DbSet<TST_COBROS_GEN_COL_USD> TST_COBROS_GEN_COL_USD { get; set; }
        public virtual DbSet<VISTA_PEDIDOS_GERENCIA> VISTA_PEDIDOS_GERENCIA { get; set; }
    }
}
