//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_OV_PagosRecibidos
    {
        public int C__OV { get; set; }
        public Nullable<System.DateTime> FECHA_OV { get; set; }
        public string DocCur { get; set; }
        public string Estado_OV { get; set; }
        public Nullable<decimal> TOTAL_OV_USD { get; set; }
        public Nullable<decimal> TOTAL_OV_COL { get; set; }
        public int C__ANTICIPO { get; set; }
        public int C__PAGO { get; set; }
        public Nullable<decimal> TOTAL_PAGO_USD { get; set; }
        public Nullable<decimal> TOTAL_PAGO_COL { get; set; }
    }
}
