//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_PEDIDOS_STOCK
    {
        public string Codigo { get; set; }
        public string Inactivo { get; set; }
        public string SuppCatNum { get; set; }
        public string Proveedor_por_defecto { get; set; }
        public string Fabricante { get; set; }
        public string ItemName { get; set; }
        public string Grupo_de_articulos { get; set; }
        public string U_SUBFAMART { get; set; }
        public string U_CLASIFICACION { get; set; }
        public Nullable<decimal> Costo_Promedio__ { get; set; }
        public Nullable<int> Minimo_Info { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> Comprometido { get; set; }
        public Nullable<decimal> Pedido { get; set; }
        public Nullable<decimal> Cant_Cotizada { get; set; }
        public Nullable<decimal> Entrada_Inv_ { get; set; }
        public Nullable<decimal> Comprado { get; set; }
        public Nullable<decimal> Vendido { get; set; }
        public Nullable<decimal> Salida_Inv_ { get; set; }
        public Nullable<decimal> Ventas_producido { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Compra { get; set; }
        public Nullable<int> Dias_Ult_Compra { get; set; }
        public Nullable<System.DateTime> Fecha_Ult__Salida { get; set; }
        public Nullable<int> Dias_Ult_Salida { get; set; }
        public Nullable<decimal> Fecha_Ult__Salida_ { get; set; }
    }
}
