//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_TBL_VENTAS_SEG_NEGOCIO
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Año { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public string Cod_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Grupo_Cliente { get; set; }
        public Nullable<decimal> Total_Neto_LOC { get; set; }
        public Nullable<decimal> Total_Neto_USD { get; set; }
    }
}
