//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_TBL_TGT
    {
        public string Clase_de_Documento { get; set; }
        public string Año_Fiscal { get; set; }
        public string Agente { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> TGT { get; set; }
    }
}
