//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVSP_COD_BARRAS
    {
        public string Cod__Articulo { get; set; }
        public string Articulo { get; set; }
        public string Cod__Barras { get; set; }
        public Nullable<short> Cod__Fabricante { get; set; }
        public string Fabricante { get; set; }
        public Nullable<short> Cod__Familia { get; set; }
        public string Familia { get; set; }
        public string DireccionQR { get; set; }
        public string Cod_Auxiliar { get; set; }
        public string Descripcion_I { get; set; }
        public string Descripcion_II { get; set; }
        public string Ubicacion { get; set; }
        public string Almacen_de_Series { get; set; }
        public string Serie { get; set; }
    }
}
