//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_VENTAS_DET_PAN
    {
        public int DocEntry { get; set; }
        public string Periodo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public string Año_Fiscal { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<short> Hora { get; set; }
        public string Almacen { get; set; }
        public string Grupo_clientes { get; set; }
        public string Cod_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Cliente_en_Factura { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public string Serie_Numeracion { get; set; }
        public Nullable<int> C__Doc { get; set; }
        public string Estado_Documento { get; set; }
        public string Cancelado { get; set; }
        public string Condicion_Credito { get; set; }
        public string Cond__Pago { get; set; }
        public string Clase_de_Documento { get; set; }
        public string Tipo_de_documento { get; set; }
        public string Usuario { get; set; }
        public string Titular_de_cuenta { get; set; }
        public string Agente { get; set; }
        public string Moneda { get; set; }
        public string Comentarios { get; set; }
        public string Marca { get; set; }
        public string Grupo_Articulos { get; set; }
        public string Proyecto { get; set; }
        public string Cod_Articulo { get; set; }
        public string Articulo { get; set; }
        public string Articulo_en_Factura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Impuesto { get; set; }
        public Nullable<decimal> Subtotal_LOC { get; set; }
        public Nullable<decimal> Descuento_CAB_LOC { get; set; }
        public Nullable<decimal> Total_Neto_LOC { get; set; }
        public Nullable<decimal> Costo_LOC { get; set; }
        public Nullable<decimal> Utilidad_LOC { get; set; }
        public Nullable<decimal> Impuesto_LOC { get; set; }
        public Nullable<decimal> Subtotal_USD { get; set; }
        public Nullable<decimal> Descuento_CAB_USD { get; set; }
        public Nullable<decimal> Total_Neto_USD { get; set; }
        public Nullable<decimal> Pendiente___sin_IMP { get; set; }
        public Nullable<decimal> Costo_USD { get; set; }
        public Nullable<decimal> Utilidad_USD { get; set; }
        public Nullable<decimal> Impuesto_USD { get; set; }
        public string Cuenta_ingresos { get; set; }
        public string Dim_1_I { get; set; }
        public string Dim_2_I { get; set; }
        public string Dim_3_I { get; set; }
        public string Dim_4_I { get; set; }
        public string Dim_5_I { get; set; }
        public string Cuenta_costos { get; set; }
        public string Dim_1_C { get; set; }
        public string Dim_2_C { get; set; }
        public string Dim_3_C { get; set; }
        public string Dim_4_C { get; set; }
        public string Dim_5_C { get; set; }
        public string Tipo_Nota { get; set; }
        public string Razon_Nota { get; set; }
        public string SubFamilia { get; set; }
        public string Clasificacion { get; set; }
    }
}
