//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_ENTREGASVSFACTURAS
    {
        public Nullable<int> NUMERO_DE_ENTREGA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string ItemCode { get; set; }
        public string ESTADO_DEL_DOC { get; set; }
        public string DOC_POSTERIOR { get; set; }
        public Nullable<int> NumFactura { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
    }
}
