//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_COMISIONES_LIN
    {
        public string Documento { get; set; }
        public string Cancelado { get; set; }
        public string Tipo_doc { get; set; }
        public string Estado { get; set; }
        public Nullable<int> C__Doc { get; set; }
        public Nullable<int> Año_doc { get; set; }
        public Nullable<int> Mes_doc { get; set; }
        public Nullable<int> Dia_doc { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_vencimiento { get; set; }
        public Nullable<int> Año_ult_pago { get; set; }
        public Nullable<int> Mes_ult_pago { get; set; }
        public Nullable<int> Dia_ult_pago { get; set; }
        public Nullable<System.DateTime> Ult_Pago { get; set; }
        public Nullable<int> Atraso { get; set; }
        public string Cliente { get; set; }
        public string Nombre_cliente { get; set; }
        public string Realizada_por { get; set; }
        public string Vendedor { get; set; }
        public string Moneda_doc { get; set; }
        public string Condicion_Credito { get; set; }
        public string Cond__Pago { get; set; }
        public Nullable<decimal> Pago_Rec_Tot { get; set; }
        public string Articulo_inventario { get; set; }
        public string Linea_impuesto { get; set; }
        public string Grupo_Articulo { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }
        public string Nombre_articulo { get; set; }
        public string Proyecto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Descuento_CAB { get; set; }
        public Nullable<decimal> Total_sin_descuento { get; set; }
        public Nullable<decimal> Costo_total { get; set; }
        public Nullable<decimal> C__Margen { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public Nullable<decimal> C__Comision_A { get; set; }
        public Nullable<decimal> Comision_A { get; set; }
        public Nullable<decimal> C___Comision_B { get; set; }
        public Nullable<decimal> Comision_B { get; set; }
        public Nullable<decimal> C__Comision_C { get; set; }
        public Nullable<decimal> Comision_C { get; set; }
        public string Cuenta_ingresos { get; set; }
        public string Dim_1_I { get; set; }
        public string Dim_2_I { get; set; }
        public string Dim_3_I { get; set; }
        public string Dim_4_I { get; set; }
        public string Dim_5_I { get; set; }
        public string Cuenta_costos { get; set; }
        public string Dim_1_C { get; set; }
        public string Dim_2_C { get; set; }
        public string Dim_3_C { get; set; }
        public string Dim_4_C { get; set; }
        public string Dim_5_C { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
    }
}
