//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_Llamada_Control_Entregas
    {
        public string Código_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public int C__OV { get; set; }
        public Nullable<System.DateTime> Fecha_OV { get; set; }
        public Nullable<System.DateTime> Fecha_de_Entrega_OV { get; set; }
        public string Articulo { get; set; }
        public string Almacen { get; set; }
        public Nullable<int> C__Entregas { get; set; }
        public Nullable<System.DateTime> Fecha_Entregas { get; set; }
        public Nullable<int> C__Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<decimal> Monto_total { get; set; }
    }
}
