//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_SALES_ZP
    {
        public Nullable<int> DocNum { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string U_CondicionVenta { get; set; }
    }
}
