//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_ORDENES_ABIERTAS
    {
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocDueDate { get; set; }
        public Nullable<decimal> Total___sin_IMP { get; set; }
        public Nullable<decimal> Pendiente_sin_facturar_OV___sin_IMP { get; set; }
        public string SlpName { get; set; }
        public string User_Code { get; set; }
        public string U_NAME { get; set; }
    }
}
