//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVSP_TST_LISTA_UBICACIONES
    {
        public int AbsEntry { get; set; }
        public string Ubicacion { get; set; }
        public string Almacen { get; set; }
        public string Pasillo { get; set; }
        public string Rack { get; set; }
        public string Estante { get; set; }
    }
}
