//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_CONTROL_PROCESOS
    {
        public Nullable<int> DocNum { get; set; }
        public string Name { get; set; }
        public string FIProject { get; set; }
        public string NombreProyecto { get; set; }
        public string CardCode { get; set; }
        public string Nombre { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Closing { get; set; }
        public string TipoDoc { get; set; }
        public Nullable<int> Num_Doc_Generado { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> C__Orden_de_Venta { get; set; }
        public Nullable<int> C__OS { get; set; }
        public Nullable<System.DateTime> Fecha_de_Entrega_OS { get; set; }
        public string Asunto_os { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public Nullable<decimal> Importe_Pendiente { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
