//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_TIZ_CANT_INV_ALMACEN
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string SuppCatNum { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> Stock_Almacen { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
    }
}
