//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_RECEPCION_LINEAS_FE
    {
        public int Id_Cabecera { get; set; }
        public string Clave { get; set; }
        public string NumeroCedulaEmisor { get; set; }
        public Nullable<int> AnioRecep { get; set; }
        public Nullable<int> MesRecep { get; set; }
        public Nullable<int> DiaRecep { get; set; }
        public string FechaHoraRecep { get; set; }
        public string FechaRecepcionFact { get; set; }
        public string HoraRecepFact { get; set; }
        public string Mensaje { get; set; }
        public string DetalleMensaje { get; set; }
        public string NumeroCedulaReceptor { get; set; }
        public string NumeroConsecutivoReceptor { get; set; }
        public System.DateTime LastTransact { get; set; }
        public string ErrDetails { get; set; }
        public string Estado { get; set; }
        public int CompanyId { get; set; }
        public string HR_envrespcode { get; set; }
        public string HR_envfecha { get; set; }
        public string HR_indestado { get; set; }
        public string HR_envdetails { get; set; }
        public int Sucursal { get; set; }
        public int Terminal { get; set; }
        public string HR_code { get; set; }
        public string HR_fecha { get; set; }
        public string TipoIdentificacionEmisor { get; set; }
        public string NombreEmisor { get; set; }
        public string TipoIdentificacionReceptor { get; set; }
        public bool TaxesTag { get; set; }
        public string CodigoActividad { get; set; }
        public string CondicionImpuesto { get; set; }
        public string NumeroConsecutivoEmisor { get; set; }
        public string NombreReceptor { get; set; }
        public string EmsrCorreoElectronico { get; set; }
        public Nullable<int> TaxFactor { get; set; }
        public string FechaEmisionXML { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TipoDocumento { get; set; }
        public string CodigoMoneda { get; set; }
        public decimal TipoCambio { get; set; }
        public string EmsrNombre { get; set; }
        public string EmsrIdeTipo { get; set; }
        public string EmsrIdeNumero { get; set; }
        public string EmsrNombreComercial { get; set; }
        public string EmsrUbProvincia { get; set; }
        public string EmsrUbCanton { get; set; }
        public string EmsrUbDistrito { get; set; }
        public string EmsrUbBarrio { get; set; }
        public string EmsrUbOtrasSenas { get; set; }
        public int EmsrTlfCodigoPais { get; set; }
        public string EmsrTlfNumTelefono { get; set; }
        public int EmsrFaxCodigoPais { get; set; }
        public string EmsrFaxNumTelefono { get; set; }
        public string RcprNombre { get; set; }
        public string RcprIdeTipo { get; set; }
        public string RcprIdeNumero { get; set; }
        public string RcprIdentificacionExtranjero { get; set; }
        public string RcprNombreComercial { get; set; }
        public string RcprUbProvincia { get; set; }
        public string RcprUbCanton { get; set; }
        public string RcprUbDistrito { get; set; }
        public string RcprUbBarrio { get; set; }
        public string RcprUbOtrasSenas { get; set; }
        public string RcprOtrasSenasExtranjero { get; set; }
        public int RcprTlfCodigoPais { get; set; }
        public string RcprTlfNumTelefono { get; set; }
        public int RcprFaxfCodigoPais { get; set; }
        public string RcprFaxfNumTelefono { get; set; }
        public string RcprCorreoElectronico { get; set; }
        public string CondicionVenta { get; set; }
        public string PlazoCredito { get; set; }
        public string MedioPago { get; set; }
        public string InfRefTipoDoc { get; set; }
        public string InfRefNumero { get; set; }
        public string InfRefFechaEmision { get; set; }
        public string InfRefCodigo { get; set; }
        public string InfRefRazon { get; set; }
        public int ConsecutivoDoc { get; set; }
        public int Id_Lineas { get; set; }
        public string PartidaArancelaria { get; set; }
        public string Codigo { get; set; }
        public string CodTipo { get; set; }
        public string CodCodigo { get; set; }
        public Nullable<decimal> BaseImponible { get; set; }
        public string ImpCodigo { get; set; }
        public Nullable<decimal> ImpTarifa { get; set; }
        public Nullable<decimal> ImpMonto { get; set; }
        public string ImpCodigoTarifa { get; set; }
        public Nullable<decimal> ImpFactorIVA { get; set; }
        public Nullable<decimal> ImpMontoExportacion { get; set; }
        public string ETipoDocumento { get; set; }
        public string EFechaEmision { get; set; }
        public string ENumeroDocumento { get; set; }
        public string ENombreInstitucion { get; set; }
        public Nullable<int> EPorcentajeExoneracion { get; set; }
        public Nullable<decimal> EMontoExoneracion { get; set; }
        public Nullable<decimal> ImpuestoNeto { get; set; }
        public int MensajeReceptorId { get; set; }
        public string OtrosDatos { get; set; }
        public int NumeroLinea { get; set; }
        public decimal Cantidad { get; set; }
        public string UnidadMedida { get; set; }
        public string UnidadMedidaComercial { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public string NaturalezaDescuento { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> MontoTotalLinea { get; set; }
        public Nullable<decimal> EMontoImpuestoV42 { get; set; }
        public Nullable<int> EPorcentajeCompraV42 { get; set; }
    }
}
