//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_FE_APPS_TRAMITE
    {
        public Nullable<int> DocNum { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public int Id { get; set; }
        public System.DateTime transactDate { get; set; }
        public string creatorUser { get; set; }
        public string notificateTo { get; set; }
        public Nullable<System.DateTime> sendingDate { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> receivedDate { get; set; }
        public Nullable<int> totalLines { get; set; }
        public string signedReport { get; set; }
    }
}
