//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_OPORTUNIDADES_DET
    {
        public int C__Oportunidad { get; set; }
        public string Nombre_Oportunidad { get; set; }
        public string Cliente { get; set; }
        public string Nombre_cliente { get; set; }
        public string Vendedor { get; set; }
        public string Creador { get; set; }
        public Nullable<System.DateTime> Contabilizacion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Porcentaje_alcanzado { get; set; }
        public string Etapa_alcanzada { get; set; }
        public Nullable<int> DocId { get; set; }
        public string Clase_documento { get; set; }
        public Nullable<int> C__Doc { get; set; }
        public Nullable<decimal> Subtotal_USD { get; set; }
        public Nullable<decimal> Descuento_CAB_USD { get; set; }
        public Nullable<decimal> Total_Neto_USD { get; set; }
    }
}
