//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_TBL_PROCESO_VENTAS
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Año { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public string Año_Fiscal { get; set; }
        public string Almacen { get; set; }
        public string Cod_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Tipo_de_documento { get; set; }
        public string Clase_de_Documento { get; set; }
        public string Estado_Documento { get; set; }
        public string Grupo_Articulos { get; set; }
        public string Cod_Articulo { get; set; }
        public string Articulo { get; set; }
        public string Articulo_en_Factura { get; set; }
        public string Marca { get; set; }
        public string Tier { get; set; }
        public string Agente { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Serie { get; set; }
        public string Localidad { get; set; }
        public Nullable<decimal> Total_Neto_LOC { get; set; }
        public Nullable<decimal> Total_Neto_USD { get; set; }
    }
}
