//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_OF
    {
        public int NUM_OF { get; set; }
        public string ARTICULO { get; set; }
        public string CODIGO_DE_PROYECTO { get; set; }
        public string ProdName { get; set; }
        public string Status { get; set; }
        public string TipoOF { get; set; }
        public string TipoProyecto { get; set; }
        public string Tipo { get; set; }
        public string ItemCode { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> BaseQty { get; set; }
        public Nullable<decimal> Costo_de_producto_real { get; set; }
        public Nullable<decimal> Costo_de_Componente_de_recurso_real { get; set; }
        public int DocNum { get; set; }
        public Nullable<int> C__OS { get; set; }
        public string Comentarions { get; set; }
        public Nullable<System.DateTime> fechaOF { get; set; }
        public Nullable<System.DateTime> fecheFinalizaion { get; set; }
    }
}
