//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_ESTADOS_GEN_EXP_V2
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Dia { get; set; }
        public string Serie_Numeración { get; set; }
        public int C__Asiento { get; set; }
        public string Clase_documento { get; set; }
        public string C__Documento { get; set; }
        public int C__Transaccion { get; set; }
        public string Comentarios { get; set; }
        public string Niv_1 { get; set; }
        public string Niv_2 { get; set; }
        public string Niv_2_N { get; set; }
        public string Niv_3 { get; set; }
        public string Niv_3_N { get; set; }
        public string Niv_4 { get; set; }
        public string Niv_4_N { get; set; }
        public string Dim_1 { get; set; }
        public string Dim_2 { get; set; }
        public string Dim_3 { get; set; }
        public string Dim_4 { get; set; }
        public string Proyecto { get; set; }
        public string Cuenta { get; set; }
        public string Nombre_Cuenta { get; set; }
        public string Cuenta_Contrapartida { get; set; }
        public string Nombre_Cuenta_Contrapartida { get; set; }
        public Nullable<decimal> Debe_LOC { get; set; }
        public Nullable<decimal> Haber_LOC { get; set; }
        public Nullable<decimal> Neto_LOC { get; set; }
        public Nullable<decimal> Debe_DOL { get; set; }
        public Nullable<decimal> Haber_DOL { get; set; }
        public Nullable<decimal> Neto_DOL { get; set; }
        public string U_Tipo { get; set; }
    }
}
