//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLVS_TIZ_OFERTAS_ABIERTAS
    {
        public int DocNum { get; set; }
        public string CardCode { get; set; }
        public string DocStatus { get; set; }
        public string Estado_Oferta { get; set; }
        public string CardName { get; set; }
        public Nullable<short> FirmCode { get; set; }
        public string Marca { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string GroupName { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string FechaDoc { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string Tier { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string SlpName { get; set; }
    }
}
