//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYD_CDR_VIEW
    {
        public Nullable<int> Boleta { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> F__Creación { get; set; }
        public Nullable<System.DateTime> F__Actualización { get; set; }
        public string Cliente { get; set; }
        public string Cod__Articulo { get; set; }
        public string No__Serie { get; set; }
        public string Descripción { get; set; }
        public string Familia { get; set; }
        public string Técnico { get; set; }
        public Nullable<decimal> Días_CDR { get; set; }
        public decimal Abrir { get; set; }
        public decimal Recepcion { get; set; }
        public decimal Diagnosticado { get; set; }
        public decimal Ofertado { get; set; }
        public decimal Orden_de_Venta_Rep { get; set; }
        public decimal Espera_Repuesto { get; set; }
        public decimal En_Produccion { get; set; }
        public decimal Reparado { get; set; }
        public decimal Facturado { get; set; }
        public Nullable<decimal> Total_Días_Hábiles { get; set; }
        public Nullable<int> Total_Días_Naturales { get; set; }
    }
}
