//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYD_CONTROL_ETAPAS
    {
        public string U_NUMOS { get; set; }
        public string U_CLIENT { get; set; }
        public string U_DETALL { get; set; }
        public string U_ETAPA { get; set; }
        public string U_TECNI { get; set; }
        public string U_OBSERV { get; set; }
        public Nullable<System.DateTime> U_FECHINI { get; set; }
        public Nullable<System.DateTime> U_FECHFIN { get; set; }
        public Nullable<decimal> U_HORAINV { get; set; }
        public string U_STATETA { get; set; }
        public string ART_DESCRIPCION { get; set; }
    }
}
