//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLAMADA_SERVICIO
    {
        public int C_OS { get; set; }
        public string CODIGO_SN { get; set; }
        public string DESCRIPCIÓN_ARTICULO { get; set; }
        public string CONTACTO { get; set; }
        public string TELEFONO { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<System.DateTime> Fecha_ENTREGA { get; set; }
        public string SERIE_FABRICANTE { get; set; }
        public Nullable<System.DateTime> Fecha_Cerrada { get; set; }
        public string C_SERIE { get; set; }
        public string MODELO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE_ARTICULO { get; set; }
        public string GRUPO_ARTICULOS { get; set; }
        public string STATUS { get; set; }
        public string PRIORIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<short> HORA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public Nullable<short> HORA_CIERRE { get; set; }
        public string ORIGEN { get; set; }
        public string TIPO_OS { get; set; }
        public string TIPO_GARANTIA { get; set; }
        public string TP_GARANTIA_PROVEEDOR { get; set; }
        public string ETAPA { get; set; }
        public string TIPO_INSPECCION { get; set; }
        public string TECNICO { get; set; }
        public string CONDICION_CREDITICIA { get; set; }
        public string STATUS_CREDITICIO { get; set; }
        public Nullable<decimal> CREDITO_DISPONIBLE { get; set; }
        public string ALM_ENTREGA { get; set; }
        public string ALM_RECEPCION { get; set; }
        public Nullable<System.DateTime> FECHA_RECEP_EQUIPO { get; set; }
        public string SUPERVISOR { get; set; }
        public string UBICACION { get; set; }
        public string PLACA_VEHICULO { get; set; }
        public string CREADO_POR { get; set; }
        public string TRATADO_POR { get; set; }
        public string COMENTARIOS { get; set; }
        public string VENDEDOR { get; set; }
        public string FABRICANTE { get; set; }
        public string ASUNTO { get; set; }
        public string COD_PROVEEDOR { get; set; }
        public string COD_PROVEEDOR2 { get; set; }
        public string COMENTARIOS_GARANTIA { get; set; }
        public string ENTREGADO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA1 { get; set; }
        public string RECLAMO_FABRICA { get; set; }
        public Nullable<decimal> Costo { get; set; }
    }
}
