//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Alistar
    {
        public int Pedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string HoraCreado { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string CodCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Vendedor { get; set; }
        public string FormaEntrega { get; set; }
        public Nullable<decimal> DocTotal { get; set; }
        public string Almacen { get; set; }
    }
}
