//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIZ_NUMERO_SERIE_ALMACEN
    {
        public string Número_de_artículo { get; set; }
        public string Número_de_catálogo_de_fabricante { get; set; }
        public string Nombre_del_fabricante { get; set; }
        public string Descripción_del_artículo { get; set; }
        public string Nombre_de_grupo { get; set; }
        public string Código_de_almacén { get; set; }
        public string Nombre_de_almacén { get; set; }
        public Nullable<decimal> En_stock { get; set; }
        public Nullable<decimal> Costo_del_artículo { get; set; }
        public Nullable<decimal> Costo_total { get; set; }
        public string Serie_del_fabricante { get; set; }
        public string Serie { get; set; }
    }
}
