//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_PEDIDOS_GERENCIA
    {
        public int N__Documento { get; set; }
        public string Nombre_Proveedor { get; set; }
        public Nullable<int> Orden_de_Venta { get; set; }
        public string CLIENTE_ { get; set; }
        public string Fecha_Despacho { get; set; }
        public string Fecha_llegada_Zebol { get; set; }
        public string Fecha_Promesa_Entrega { get; set; }
        public string Comentarios { get; set; }
        public string Estatus { get; set; }
        public string Tipo_OC { get; set; }
        public string Vendedor { get; set; }
        public Nullable<decimal> Monto_Orden_Compra__ { get; set; }
        public Nullable<decimal> Monto_Orden_Venta__ { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Codigo_Articulo_Compra { get; set; }
        public string Descripción { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Fabricante { get; set; }
    }
}
